name: Multi Environment Deployment

on:
  push:
    branches:
      - dev
      - qa
      - main

  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        required: true
        type: choice
        options:
          - dev
          - qa
          - prod

permissions:
  contents: read
  id-token: write

env:
  RESOURCE_GROUP: Hosp-Task-26
  IMAGE_NAME: hospital-api

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      # -----------------------------------------
      # 1. Checkout
      # -----------------------------------------

      - name: Checkout
        uses: actions/checkout@v4


      # -----------------------------------------
      # 2. Azure Login
      # -----------------------------------------

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}


      # -----------------------------------------
      # 3. Decide Environment
      # -----------------------------------------

      - name: Decide Environment
        shell: bash
        run: |

          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then

            ENV="${{ github.event.inputs.environment }}"

          elif [ "${GITHUB_REF_NAME}" = "dev" ]; then

            ENV="dev"

          elif [ "${GITHUB_REF_NAME}" = "qa" ]; then

            ENV="qa"

          elif [ "${GITHUB_REF_NAME}" = "main" ]; then

            ENV="prod"

          else

            echo "Invalid branch"
            exit 1

          fi

          echo "DEPLOY_ENV=$ENV" >> "$GITHUB_ENV"

          echo "Environment = $ENV"


      # -----------------------------------------
      # 4. Select ACR
      # -----------------------------------------

      - name: Select ACR
        shell: bash
        run: |

          if [ "$DEPLOY_ENV" = "dev" ]; then

            echo "ACR_NAME=hospdevacr26" >> "$GITHUB_ENV"
            echo "ACR_LOGIN_SERVER=hospdevacr26.azurecr.io" >> "$GITHUB_ENV"
            echo "APP_NAME=hospital-dev" >> "$GITHUB_ENV"

          elif [ "$DEPLOY_ENV" = "qa" ]; then

            echo "ACR_NAME=hospacrqa" >> "$GITHUB_ENV"
            echo "ACR_LOGIN_SERVER=hospacrqa.azurecr.io" >> "$GITHUB_ENV"
            echo "APP_NAME=hospital-qa" >> "$GITHUB_ENV"

          elif [ "$DEPLOY_ENV" = "prod" ]; then

            echo "ACR_NAME=hospacr26" >> "$GITHUB_ENV"
            echo "ACR_LOGIN_SERVER=hospacr26.azurecr.io" >> "$GITHUB_ENV"
            echo "APP_NAME=hospital-prod" >> "$GITHUB_ENV"

          else

            echo "Invalid environment"
            exit 1

          fi

          echo "ACR = $ACR_NAME"
          echo "Server = $ACR_LOGIN_SERVER"
          echo "App = $APP_NAME"


      # -----------------------------------------
      # 5. Login to selected ACR
      # -----------------------------------------

      - name: Login to ACR
        run: |

          az acr login --name "$ACR_NAME"


      # -----------------------------------------
      # 6. Generate NEW image tag
      # -----------------------------------------

      - name: Generate Image Tag
        shell: bash
        run: |

          VERSION="${{ vars.VERSION }}"

          BUILD="${{ github.run_number }}"

          IMAGE_TAG="v${VERSION}-${DEPLOY_ENV}-b${BUILD}"

          echo "IMAGE_TAG=$IMAGE_TAG" >> "$GITHUB_ENV"

          echo "======================================"
          echo "NEW IMAGE TAG"
          echo "$IMAGE_TAG"
          echo "======================================"


      # -----------------------------------------
      # 7. Build
      # -----------------------------------------

      - name: Build Docker Image
        run: |

          docker build \
            -t "$ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG" \
            .


      # -----------------------------------------
      # 8. Push NEW image to ACR
      # -----------------------------------------

      - name: Push Docker Image
        run: |

          docker push \
            "$ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG"


      # -----------------------------------------
      # 9. Deploy Container App
      # -----------------------------------------

      - name: Deploy Container App
        run: |

          az containerapp update \
            --name "$APP_NAME" \
            --resource-group "$RESOURCE_GROUP" \
            --image "$ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG"


      # -----------------------------------------
      # 10. Verify
      # -----------------------------------------

      - name: Verify Deployment
        run: |

          echo "======================================"
          echo "Deployment completed"
          echo "======================================"

          echo "Environment : $DEPLOY_ENV"
          echo "Registry    : $ACR_NAME"
          echo "Image       : $IMAGE_TAG"
          echo "Container   : $APP_NAME"

          echo ""
          echo "Current image:"

          az containerapp show \
            --name "$APP_NAME" \
            --resource-group "$RESOURCE_GROUP" \
            --query "properties.template.containers[0].image" \
            -o tsv